spring.application.name=loginApi

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5434/controle_animal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Formatacao de datas
spring.mvc.format.date=yyyy/M/d

# Swagger
springdoc.swagger-ui.path=/swagger-ui/index.html

# Token
api.security.token.secret=${JWT_SECRET:my-secret-key}

# Logging
logging.level.org.springframework.security=TRACE
